{{- range .Values.backends }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: {{ .name }}
  namespace: {{ include "ai-gateway.namespace" $ }}
  labels:
{{ include "ai-gateway.labels" $ | indent 4 }}
spec:
  endpoints:
{{- range .endpoints }}
    - fqdn:
        hostname: {{ .host }}
        port: {{ .port }}
{{- end }}
---
{{- end }}
