{{- if .Values.envoyProxy.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ .Values.envoyProxy.name | default (include "ai-gateway.name" .)  }}
  namespace: {{ include "ai-gateway.namespace" . }}
  labels:
{{ include "ai-gateway.labels" $ | indent 4 }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer  # or NodePort, LoadBalanc
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      envoyDeployment:
        container:
          image: {{ .Values.envoyProxy.image }}
{{- end }}
