apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ default (include "ai-gateway.name" .) .Values.gateway.name }}
  namespace: {{ include "ai-gateway.namespace" . }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end}}
  labels:
{{ include "ai-gateway.labels" $ | indent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName | default .Values.global.gatewayClassName | default (include "ai-gateway.name" .)  }}
  {{- if .Values.envoyProxy.enabled }}
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: {{ .Values.envoyProxy.name | default (include "ai-gateway.name" .)  }}
  {{- end }}
  listeners:
  {{- toYaml .Values.gateway.listeners | nindent 2 }}
