{{- range .Values.aiServiceBackends }}
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: {{ .name }}
  namespace: {{ include "ai-gateway.namespace" $ }}
  labels:
{{ include "ai-gateway.labels" $ | indent 4 }}
spec:
  schema:
    name: {{ .schemaName }}
    {{- if .version }}
    version: {{ .version }}
    {{- end }}
  backendRef:
    name: {{ .backendRef }}
    kind: Backend
    group: gateway.envoyproxy.io
---
{{- end }}
