apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: '{{default (include "ai-gateway.name" .)}}-limit'
  namespace: {{ include "ai-gateway.namespace" $ }}
  labels:
{{ include "ai-gateway.labels" $ | indent 4 }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ default (include "ai-gateway.name" .) .Values.gateway.name }}
  connection:
    bufferLimit: 150Mi
