{{- if and .Values.envoyProxy.enabled .Values.envoyProxy.create }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ .Values.envoyProxy.name | default (include "ai-gateway.name" .)  }}
  namespace: {{ include "ai-gateway.namespace" . }}
  labels:
{{ include "ai-gateway.labels" $ | indent 4 }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: {{ .Values.envoyProxy.envoyService.type | default "LoadBalancer" }}  # or NodePort, LoadBalancer
        {{- with .Values.envoyProxy.envoyService.annotations }}
        annotations:
          {{ toYaml . | nindent 10 }}
        {{- end }}
      envoyDeployment:
        container:
          image: {{ .Values.envoyProxy.image }}
{{- end }}
