{{- if .Values.gatewayClass.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gatewayClass.name | default .Values.global.gatewayClassName | default (include "ai-gateway.name" .)  }}
  labels:
{{ include "ai-gateway.labels" $ | indent 4 }}
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
{{- end }}
