name: Release Helm Chart to GitHub Pages

on:
  push:
    tags:
      - '*.*.*'   # Only run on version tag pushes like 1.2.3

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Set Chart version from tag using yq
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          yq -i ".version = \"${TAG_NAME}\"" charts/envoy-aigw-provisioner/Chart.yaml
          cat charts/envoy-aigw-provisioner/Chart.yaml

      - name: Install just
        run: |
          sudo apt-get update
          sudo apt-get install -y just

      - name: Run pre-commit checks
        run: |
          just _install-plugins
          just pre-commit

      - name: Run helm-docs
        uses: losisin/helm-docs-github-action@v1

      - name: Generate Chart readme
        run: helm-docs

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
