name: Release Helm Chart to GitHub Pages

on:
  push:
    tags:
      - '*.*.*'   # Only run on version tag pushes like 1.2.3

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Set Chart version from tag using yq
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          yq -i ".version = \"${TAG_NAME}\"" chart/Chart.yaml

      - name: Install just
        run: |
          sudo apt-get update
          sudo apt-get install -y just

      - name: Run pre-commit checks
        run: |
          just _install-plugins
          just pre-commit

      - name: "install helm-docs"
        run: go install github.com/norwoodj/helm-docs/cmd/helm-docs@latest

      - name: Generate Chart readme
        run: helm-docs

      - name: Package chart
        run: |
          helm package chart --destination packaged

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy chart package to gh-pages
        run: |
          mkdir -p gh-pages/
          cp packaged/*.tgz gh-pages/

      - name: Update Helm repo index
        run: |
          REPO_OWNER="${GITHUB_REPOSITORY_OWNER}"
          REPO_NAME="$(basename ${GITHUB_REPOSITORY})"
          cd gh-pages
          helm repo index . --url "https://$REPO_OWNER.github.io/$REPO_NAME"
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

      - name: Commit and push changes
        run: |
          cd gh-pages
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update Helm chart repo [skip ci]" || echo "No changes to commit"
          git push origin gh-pages
