name: pre-commit checks

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install just
        run: |
          sudo apt-get update
          sudo apt-get install -y just

      - name: Run just pre-commit
        run: just pre-commit
